---
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: no-commit-to-branch
        args: [--branch, main, --branch, develop]
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: pretty-format-json
        args: [--autofix]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
